### ISSUE TITLE
Drill Kit 

### ISSUE THREAD

**Issue by ChewedPencil** [BurgerLUA/burgerstation#263] opened 2021-07-06 18:00 UTC
AS of right now, if you have multiple drill kits in your inventory, using one will use the charges of all three at once

**Comment by BurgerLUA** [comment] 2021-07-07 22:48
I can't reproduce this. It might be just a different bug that was just fixed.

**Comment by BurgerLUA** [comment] 2021-07-28 10:04
This was a bug due to saving/loading. Its fixed now.

**Closed by BurgerLUA** 2021-07-28 10:04 UTC
